# Generated by Django 5.2.8 on 2025-11-22 09:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileGadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('memory_volume', models.CharField(db_index=True, max_length=255)),
                ('price_use', models.CharField(db_index=True, max_length=255)),
                ('price_action', models.CharField(db_index=True, max_length=255)),
                ('pic_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('product_code', models.CharField(db_index=True, max_length=50)),
                ('review_count', models.IntegerField(blank=True, db_index=True, null=True)),
                ('series', models.CharField(db_index=True, max_length=255)),
                ('display_size', models.CharField(db_index=True, max_length=255)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MobileGadget',
            },
        ),
    ]
