# Generated by Django 5.2.8 on 2025-11-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_mobilegadget_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilegadget',
            name='price_action',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
